package pl.pozsda19.electroshop.domain;

public enum Group {
    OBUDOWY, WSZYSTKIE, WIRNIKI, REZYSTORY, WLACZNIKI, PRZEKLADNIE
    , LOZYSKA, STOJANY, STYKI, POZOSTALE, REKOJESCI, MAGNESY, KOLAZEBATE
    , SZCZOTKOTRZYMACZE, SRUBY_WKRETY, USZCZELNIACZE
    , ORINGI, SILNIKI, KORBOWODY, PASKI, SZCZOTKI, WKRETARKI
    , OLEJDOSMAROWANIALANCUCHAPILY
    , LANCUCHDOPILLANCUCHOWYCH, PROWADNICEDOPILLANCUCHOWYCH
    , BERNER, BOSCH, MAKITA, DEWALT
    , NOZYCEDOZYWOPLOTU, LAMPY, WIERNICERDZENIOWE, UKOSNICE
    , WYRZYNARKI, DOOBROBKISTALINIERDZEWNEJISZLACHETNEJ, SZLIFIERKIPROSTE
    , SZLIFIERKIKATOWE, MLOTOWIERTARKI, WIERTARKI, WIERTARKOWKRETARKI
    , PISTOLETYDONAKLADANIAKLEJOWISILIKONU, PILARKIBRZESZCZOTOWE, ZESTAWY
    , KLUCZEUDAROWE, PILARKITARCZOWE
    , WIERTARKI_WKRETARKIKATOWE
    , PISTOLETYDOZSZWEKIGWOZDZI, NOZYCEDOBLACHY, ODKURZACZEWARSZTATOWE, OPALARKI
    , MLOTYUDAROWOOBROTOWEIUDAROWE, PILY, FREZARKIISTRUGI, SZLIFIERKI;
}
