package pl.pozsda19.electroshop.domain;

public enum SubCategory {

    UŻYWANY, NOWY, POZIOMICA, LASER, WYKRYWACZ, DALMIERZ, USŁUGATRANSPORTOWA, WALIZKA, KLUCZNASADOWY, TARCZAPILARSKA,
    OSPRZĘTPIŁAŁAŃCUCHOWA, BRZESZCZOT, UCHWYTWIERTARSKI, ŁADOWARKA, TARCZADIAMENTOWA, LATARKA,
    WIERTŁO, DŁUTO, AKUMULATOR, SIECIOWE, POZOSTAŁE;
}
