package pl.pozsda19.electroshop.domain;

public enum SubCategory {

    UZYWANE_OBUDOWY, UZYWANE_WSZYSTKIE, UZYWANE_WIRNIKI, UZYWANE_REZYSTORY, UZYWANE_WLACZNIKI, UZYWANE_PRZEKLADNIE
    ,NOWE_LOZYSKA, NOWE_STOJANY, NOWE_STYKI, NOWE_POZOSTALE,NOWE_REKOJESCI,NOWE_MAGNESY, NOWE_KOLAZEBATE
    , NOWE_SZCZOTKOTRZYMACZE,NOWE_SRUBY_WKRETY, NOWE_WIRNIKI, NOWE_REZYSTORY, NOWE_OBUDOWY, NOWE_USZCZELNIACZE
    ,NOWE_ORINGI, NOWE_WLACZNIKI, NOWE_SILNIKI, NOWE_KORBOWODY, NOWE_PRZEKLADNIE, NOWE_PASKI, NOWE_SZCZOTKI, NOWE_WKRETARKI
    ,POZOSTALE, POZIOMICE, LASERY, WYKRYWACZE, DALMIERZE
    ,USLUGITRANSPORTOWE, WALIZKI, KLUCZENASADOWE, TARCZAPILARSKA, OSPRZETDOPILLANCUCHOWYCH_OLEJDOSMAROWANIALANCUCHAPILY
    ,OSPRZETDOPILLANCUCHOWYCH_LANCUCHDOPILLANCUCHOWYCH, OSPRZETDOPILLANCUCHOWYCH_PROWADNICEDOPILLANCUCHOWYCH
    ,UCHWYTYWIERTARSKIE_BERNER, UCHWYTYWIERTARSKIE_BOSCH, UCHWYTYWIERTARSKIE_MAKITA, UCHWYTYWIERTARSKIE_DEWALT
    , LADOWARKI, TARCZEDIAMENTOWE, LATARKI, WIERTLA, DLUTA, AKUMULATORY
    , AKUMULATOROWE_NOZYCEDOZYWOPLOTU, AKUMULATOROWE_LAMPY, AKUMULATOROWE_WIERNICERDZENIOWE, AKUMULATOROWE_UKOSNICE
    ,AKUMULATOROWE_WYRZYNARKI, AKUMULATOROWE_DOOBROBKISTALINIERDZEWNEJISZLACHETNEJ, AKUMULATOROWE_SZLIFIERKIPROST
    ,AKUMULATOROWE_SZLIFIERKIKATOWE, AKUMULATOROWE_MLOTOWIERTARKI, AKUMULATOROWE_WIERTARKI, AKUMULATOROWE_WIERTARKOWKRETARKI
    ,AKUMULATOROWE_PISTOLETYDONAKLADANIAKLEJOWISILIKONU, AKUMULATOROWE_PILARKIBRZESZCZOTOWE, AKUMULATOROWE_ZESTAWY
    ,AKUMULATOROWE_KLUCZEUDAROWE, AKUMULATOROWE_PILARKITARCZOWE, AKUMULATOROWE_WKRETARKI
    , AKUMULATOROWE_WIERTARKI_WKRETARKIKATOWE
    , SIECIOWE_PISTOLETYDOZSZWEKIGWOZDZI, SIECIOWE_NOZYCEDOBLACHY, SIECIOWE_ODKURZACZEWARSZTATOWE, SIECIOWE_OPALARKI
    , SIECIOWE_MLOTYUDAROWOOBROTOWEIUDAROWE, SIECIOWE_PILY, SIECIOWE_FREZARKIISTRUGI, SIECIOWE_SZLIFIERKI
    , SIECIOWE_WIERTARKI, SIECIOWE_WKRETARKI;

}
