package pl.pozsda19.electroshop.domain;

public enum Subcategory {

UZYWANE, NOWE, POZOSTALE, POZIOMICE, LASERY, WYKRYWACZE, DALMIERZE, USLUGITRANSPORTOWE
    , WALIZKI, KLUCZENASADOWE, TARCZAPILARSKA, OSPRZETDOPILLANCUCHOWYCH, BRZESZCZOTY, UCHWYTYWIERTARSKIE
    , LADOWARKI, TARCZEDIAMENTOWE, LATARKI, WIERTLA, DLUTA, AKUMULATORY, AKUMULATOROWE, SIECIOWE;

}
